### ISSUE TITLE
var bool

### ISSUE THREAD

**Issue by rjmk** [jackpandas/tt#1]
This is super cool! Do you have any links where I can start learning about jade?

Also, in your scripts.js file, I don't think your variable bool actually does anything. You should be able to delete lines 5-9 without effect.

window.find is smart! I'm definitely stealing that.

**Comment by jackpandas** [comment]
Hi Rafe, only just saw this! I'll check out the bool issue, think it's a case of not knowing how to run tests at that point. I pretty much picked up jade from the documentation, even though it's not that good...
